# Update Checker Settings
update-checker:
  enable: true
  console: true # Post message to console
  op: true # Send update notification to opped players on join

# Language, specify the language file to use, for example `en_US` which will load `/lang/en_US.json`
language: "en_US"

# Put here the worlds where the plugin is allowed to frun.
allowed-worlds:
  - "world"

# Edit here the spawn location of the plugin.
lobby-spawn-location:
  world:
  x:
  y:
  z:
  yaw:
  pitch: